version: "3.3"

services:
  app1:
    build: .
    environment:
      - DB_PATH=/data/user.db
    volumes:
      - ./data:/data

  app2:
    build: .
    environment:
      - DB_PATH=/data/user.db
    volumes:
      - ./data:/data

  app3:
    build: .
    environment:
      - DB_PATH=/data/user.db
    volumes:
      - ./data:/data

  proxy:
    image: nginx:alpine
    ports:
      - "5050:5050"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
